<?php

/**
 * @file
 * Allows to flexibly create, browse and select entities.
 */

use \Drupal\Core\Form\FormStateInterface;
use \Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 *
 * Overrides the core html theme to use a custom template for iframes.
 */
function entity_browser_theme() {
  return [
    'html__entity_browser__iframe' => [
      'template' => 'html--entity-browser--iframe',
      'render element' => 'html',
      'preprocess functions' => ['template_preprocess_html']
    ],
    'html__entity_browser__modal' => [
      'template' => 'html--entity-browser--iframe',
      'render element' => 'html',
      'preprocess functions' => ['template_preprocess_html']
    ],
    'page__entity_browser__iframe' => [
      'template' => 'page--entity-browser--iframe',
      'render element' => 'html',
      'preprocess functions' => ['template_preprocess_page']
    ],
    'page__entity_browser__modal' => [
      'template' => 'page--entity-browser--iframe',
      'render element' => 'html',
      'preprocess functions' => ['template_preprocess_page']
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function entity_browser_form_alter(&$form, FormStateInterface &$form_state) {
  if ($form['#form_id'] == 'views_exposed_form' && $form_state->getStorage()['display']['display_plugin'] == 'entity_browser') {
    // Exposed form is not a "real" form when used in context of entitity browser.
    // Let's just display form elements.
    $dummy_form = array();
    /** @var \Drupal\views\ViewExecutable $view */
    $view = $form_state->get('view');
    /** @var \Drupal\views\Plugin\views\filter\FilterPluginBase $filter */
    foreach ($view->filter as $filter) {
      if ($filter->isExposed()) {
        $exposed = $filter->exposedInfo();
        $dummy_key = 'entity_browser_exposed_' . $exposed['value'];
        $dummy_form[$dummy_key] = $form[$exposed['value']];
        $dummy_form['#info']['filter-' . $dummy_key] = $form['#info']['filter-' . $filter->field];
        $dummy_form['#info']['filter-' . $dummy_key]['value'] = $dummy_key;
      }
    }
    $dummy_form['#id'] = '';
    $dummy_form['#build_id'] = '';
    $dummy_form['#array_parents'] = [];
    $dummy_form['#tree'] = '';
    $dummy_form['#theme'] = $form['#theme'];
    $form = $dummy_form;
  }
}
