<?php

/**
 * @file
 * Allows to flexibly create, browse and select entities.
 */

use \Drupal\Core\Form\FormStateInterface;
use \Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 *
 * Overrides the core html theme to use a custom template for iframes.
 */
function entity_browser_theme() {
  return [
    'html__entity_browser__iframe' => array(
      'template' => 'html--entity-browser--iframe',
      'render element' => 'html',
      'preprocess functions' => ['template_preprocess_html']
    ),
  ];
}

/**
 * Implements hook_form_alter().
 */
function entity_browser_form_alter(&$form, FormStateInterface &$form_state) {
  if ($form['#form_id'] == 'views_exposed_form' && $form_state->getStorage()['display']['display_plugin'] == 'entity_browser') {
    $dummy_form = array();
    foreach (Element::getVisibleChildren($form) as $key) {
      if ($key !== 'actions') {
        $dummy_form[$key] = $form[$key];
      }
    }
    $form = $dummy_form;
  }
}
