field.widget.third_party.entity_browser_entity_form:
  type: mapping
  label: 'IEF entity browser existing functionality'
  mapping:
    entity_browser_id:
      type: string
      label: ID of entity browser to be used as replacement for autocomplete field

entity_browser.browser.widget.entity_form:
  type: mapping
  label: 'Entity form widget configuration'
  mapping:
    submit_text:
      type: string
      label: 'Submit button text'
    entity_type:
      type: string
      label: 'Entity type ID'
    bundle:
      type: string
      label: 'Bundle ID'
    form_mode:
      type: string
      label: 'Form display mode ID'

field.widget.settings.inline_entity_form_complex:
  type: mapping
  label: 'Inline entity form widget'
  mapping:
    form_mode:
      type: string
      label: 'Form mode'
    override_labels:
      type: boolean
      label: 'Override labels'
    label_singular:
      type: string
      label: 'Label for singular entity'
    label_plural:
      type: string
      label: 'Label for multiple entities'
    allow_new:
      type: boolean
      label: 'Allow new entities'
    allow_existing:
      type: boolean
      label: 'Allow existing entities'
    match_operator:
      type: string
      label: 'Match operator'